dist: trusty
language: php
php:
  #- 5.4
  #- 5.5
  #- 5.6
  - 7.0

env:
  global:
    - COMPOSER_BIN_DIR=~/bin
  matrix:
    - CODING_STANDARD=Ecg SEVERITY=5
    - CODING_STANDARD=MEQP1 SEVERITY=5
    - CODING_STANDARD=MEQP1 SEVERITY=9

matrix:
  allow_failures:
    - env: CODING_STANDARD=Ecg SEVERITY=5
    - env: CODING_STANDARD=MEQP1 SEVERITY=5

before_install: test -n "$GITHUB_TOKEN" && composer config github-oauth.github.com "$GITHUB_TOKEN" || true
install: composer install --no-interaction --prefer-dist

before_script: phpcs --config-set installed_paths vendor/magento-ecg/coding-standard,vendor/magento/marketplace-eqp
script: phpcs ./ --ignore=./vendor --standard="$CODING_STANDARD" --severity="$SEVERITY" --extensions=phtml,php,js,css

#notifications:
#  slack: ebizmarts:DqCqxnqWzW55zoFU069hxs1T
