dist: trusty
language: php
php:
  #- 5.4
  #- 5.5
  #- 5.6
  - 7.0

env:
  - TEST_SUITE=ecg_coding_standards
  - TEST_SUITE=marketplate_eqp

before_script:
  - sleep 30

script:
  - cd ..
  - sh -c "if [ '$TEST_SUITE' = 'marketplate_eqp' ]; then composer require magento/marketplace-eqp && vendor/squizlabs/php_codesniffer/scripts/phpcs --config-set installed_paths /home/travis/build/mailchimp/vendor/magento/marketplace-eqp-1.0.5/ && vendor/squizlabs/php_codesniffer/scripts/phpcs -n --standard="MEQP1" ./mc-magento/; fi"
  - sh -c "if [ '$TEST_SUITE' = 'ecg_coding_standards' ]; then composer require magento-ecg/coding-standard && composer require squizlabs/php_codesniffer && vendor/squizlabs/php_codesniffer/scripts/phpcs --config-set installed_paths /home/travis/build/mailchimp/vendor/magento-ecg/coding-standard && vendor/squizlabs/php_codesniffer/scripts/phpcs -n --standard="EcgM2" ./mc-magento/; fi"

#notifications:
#  slack: ebizmarts:DqCqxnqWzW55zoFU069hxs1T