dist: trusty
language: php
php:
  #- 5.4
  #- 5.5
  - 5.6
  - 7.0

env:
  global:
    - COMPOSER_BIN_DIR=~/bin
    - CODE_EXTENSIONS=phtml,php,js,css
  matrix:
    - TEST_SUITE=marketplace_review
    - TEST_SUITE=unit
    - TEST_SUITE=ecg_coding_standards
    - TEST_SUITE=meqp1_coding_standards

matrix:
  allow_failures:
    - env: TEST_SUITE=ecg_coding_standards
    - env: TEST_SUITE=meqp1_coding_standards

before_install: test -n "$GITHUB_TOKEN" && composer config github-oauth.github.com "$GITHUB_TOKEN" || true
install: composer install --no-interaction --prefer-dist

before_script: phpcs --config-set installed_paths vendor/magento-ecg/coding-standard,vendor/magento/marketplace-eqp
script:
  - |
    if [ "$TEST_SUITE" = "marketplace_review" ]; then
      phpcs ./ --ignore=./vendor --extensions="$CODE_EXTENSIONS" --standard="MEQP1" --severity="10"
    fi
  - |
    if [ "$TEST_SUITE" = "ecg_coding_standards" ]; then
      phpcs ./ --ignore=./vendor --extensions="$CODE_EXTENSIONS" --standard="Ecg"
    fi
  - |
    if [ "$TEST_SUITE" = "meqp1_coding_standards" ]; then
      phpcs ./ --ignore=./vendor --extensions="$CODE_EXTENSIONS" --standard="MEQP1"
    fi
  - sh -c "if [ '$TEST_SUITE' = 'unit' ]; then wget http://ebizmartsbackup.s3.amazonaws.com/magento-1.9.2.4-2016-02-23-06-07-06.tar.bz2 && tar xjf magento-1.9.2.4-2016-02-23-06-07-06.tar.bz2 && cd magento && /bin/cp -r ../mc-magento/* . && cd tests/unit && wget https://phar.phpunit.de/phpunit-4.8.phar && php phpunit-4.8.phar; fi"

#notifications:
#  slack: ebizmarts:DqCqxnqWzW55zoFU069hxs1T
